# Generated by Django 4.2.4 on 2023-10-02 19:02

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='blog_title', unique=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
